Validate contact form
Krishnabot/Portfolio_old pull request #10
Opened 2022-06-16 15:53 UTC by Krishnabot

In this pull request
1. When the user submits the form, check if the email is in lower case.
2. If the validation is OK, the form is sent.
3. If the validation is not OK,  shows an error message to the user near the submit button informing them of the error, and the form is not sent.

2022-06-16 16:03 UTC, danmainah requested changes
Hi @Krishnabot , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has contributions from one individual, and it's a group project, kindly ensure everyone contributes to the project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-06-16 16:55 UTC, tufoinnkuo10 requested changes
Hi @Krishnabot 

Great job so far for doing the good work on your own. nevertheless, there are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Github flow
✅ Descriptive pull request message
✅ linter error checks validated
✅email checks for lowercase well
✅ error message shows

# Required Changes ♻️
Check the comments under the review

![tufoin](https://media.giphy.com/media/vQGBDTkhtIunaJYmRF/giphy.gif)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-06-16 16:55 UTC, tufoinnkuo10 commented on script.js
> +    email.setCustomValidity('Email must be lowercase. Please Try agin');
- [ ] Great job.. your validation works well. one little issue, kindly make the error message to show beside the submit button. 
- [ optional] you can make the font color red so the warning is noticed

2022-06-17 07:26 UTC, tufoinnkuo10 requested changes
Hi @Krishnabot 

There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Github flow
✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ form works well


Required Changes ♻️
Check the comments under the review
Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-06-17 07:26 UTC, tufoinnkuo10 commented on script.js
> +      .setCustomValidity('Email must be lowercase. Please Try agin');
- [ ] validation works correctly, the error message is in the right position but the form doesn't submit even when the email is in lowercase. rather it keeps giving the error message when I try to submit. 
![Screenshot (155)](https://user-images.githubusercontent.com/65298048/174247472-aeb219db-4dff-477d-97a9-7353640df79e.png)

2022-06-17 15:45 UTC, roshan-bajgain approved these changes
Hi @Krishnabot, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️
- Professional README file. ✔️
- PR has a good title and summary. ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-17 15:48 UTC, merged