Portfolio: Mobile version skeleton
Krishnabot/Portfolio_old pull request #2
Opened 2022-05-27 20:11 UTC by Krishnabot

In this project

- HTML and CSS files for work and about and contact sections created and tested. 

- github flow created.

- linter set up and checked for any linting errors.

2022-05-27 21:46 UTC, jaflih requested changes
Hi @Krishnabot  , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
✔️ Linters passed 💯
✔️ The content is aligned with flexbox 🥇 
✔️ Great commit history

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @jaflih in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-27 21:46 UTC, jaflih commented on index.html
> +        <div class="projects">
Kindly change the `div` by `section`, the semantic help the browser to know witch section it gonna display as well.

2022-05-27 21:46 UTC, jaflih commented on index.html
> +        <div class="projects">
Please kindly change your code for using `CSS grid ` with `Flexbox` to layout elements like asked in the requirement: 

<img width="1032" alt="image" src="https://user-images.githubusercontent.com/7243132/170785187-75a4539e-aebc-44a0-abcf-4c35b06bf07c.png">

2022-05-27 21:46 UTC, jaflih commented on index.html
> +            </div>
Please, kindly change your code using `ul/li `as asked in the requirement:

<img width="1032" alt="image" src="https://user-images.githubusercontent.com/7243132/170786462-784a8f61-1bf7-4872-816f-574c57f0468c.png">

2022-05-27 21:46 UTC, jaflih commented on index.html
> +            </div>
Please ensure your button are conform to the design guidelines by Figma:

Your design
<img width="234" alt="image" src="https://user-images.githubusercontent.com/7243132/170786958-e5093dce-2d1b-41ce-bc6b-c0f94663dc31.png">

Figma:
<img width="259" alt="image" src="https://user-images.githubusercontent.com/7243132/170787011-103c0e50-d145-444b-9e20-e48a1f0437f3.png">

2022-05-27 21:46 UTC, jaflih commented on index.html
> +        <div class="about-myself">
Kindly change the `div` by `section`, the semantic help the browser to know which section it gonna display as well.

2022-05-27 21:46 UTC, jaflih commented on index.html
> +        <button type="button">Get my resume</button>
Please ensure your button hover effects conform to the design guidelines by Figma:

<img width="642" alt="image" src="https://user-images.githubusercontent.com/7243132/170787864-4df4db96-7cd1-4f77-a2fb-dcd69781e4ca.png">

2022-05-27 21:46 UTC, jaflih commented on index.html
> +                <p>Languages</p>
Please, kindly change your code (add `ul/li`) to follow the requirement:

<img width="944" alt="image" src="https://user-images.githubusercontent.com/7243132/170788459-b6d6cd6e-3239-4278-89ec-9e788611f7c9.png">

2022-05-27 21:46 UTC, jaflih commented on index.html
> +        <div class="about-myself">
Please, use `Flexbox` to layout this section.  Using Flexbox will facilitate the design when you will do the Desktop view.

2022-05-27 21:46 UTC, jaflih commented on style.css
> +  position: relative;
[OPTIONAL]Please, don't use the position: relative;`, instead use margin/padding if you want to space element. The problem is that you give a height to your section, that's why you have this problem. 

<img width="217" alt="image" src="https://user-images.githubusercontent.com/7243132/170789382-00bb2f17-fbc4-425d-8c01-2682de84d56d.png">

Please, remove it and add margin/padding to have a professional project.

2022-05-28 10:53 UTC, vic778 approved these changes
Hi @Krishnabot  , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Charlie Brown](https://media.giphy.com/media/ZdO4NenDbsQNwUwKDB/giphy.gif)

## Highlights

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification

2022-05-28 11:06 UTC, merged