Mobile menu
Krishnabot/Portfolio_old pull request #8
Opened 2022-06-15 17:26 UTC by Krishnabot

In this pull request:

1. HTML, CSS, and javascript Linters are added.
2. HTML, CSS, and javascript codes are tested.
3. Functionality added When the user clicks the hamburger button, the mobile menu appears.
4. Functionality added When the user clicks the close (X) button, the mobile menu disappears.
5. Functionality added When the user clicks any of the mobile menu options, the mobile menu disappears.
6. Functionality added When the user clicks any of the mobile menu options, a correct part of the page is displayed.
7. live Demo of the project added. 
.

2022-06-15 21:33 UTC, OLIPLICHE requested changes
Hi @Krishnabot , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
Linter is green (the last commit have a green check mark (✅)) 👏
README file is descriptive 👏
Commit messages are meaningful 👏 👏
Github flow is correctly used (Pull Request is made from the feature branch into the main branch) 👏

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [ ] You can also consider:

- Please adjust the margins, and paddings, and make the `header` look like the original one.
- Your image: 
![a](https://user-images.githubusercontent.com/63972670/173933206-ca79e5c8-0e70-4ca2-90f0-1e15498a6d6f.PNG)
- Original 
![d](https://user-images.githubusercontent.com/63972670/173933483-f25344e1-8721-47c1-9a14-8fb6db07032b.PNG)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-15 21:33 UTC, OLIPLICHE commented on index.html
>              <div class="hamburger">
- [ ] Please your hamburger button and menu should follow the design from [the chosen template in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1) (e.g., font, colors, images, tests, margins).
- Your Design
 ![b](https://user-images.githubusercontent.com/63972670/173932332-d48417ff-b6ff-4c77-9456-e0a365872beb.PNG)

- Original Design   
![c](https://user-images.githubusercontent.com/63972670/173932547-95a23342-fef4-4392-bd6a-5c2c86912fce.PNG)

2022-06-16 06:14 UTC, sja-thedude requested changes
## Required Changes ♻️

Hi @Krishnabot, This is @sja-thedude your code reviewer.

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![200w](https://user-images.githubusercontent.com/70269507/159484303-3187dacc-4a82-4263-bb1a-8d72417ce1d9.gif)

 ## Highlights
✔️ Good jo so far

 ## Required Changes ♻️
- [ ] _Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-16 06:14 UTC, sja-thedude commented on script.js
> +    myFunction();
- [ ] Kindly make sure to follow the background for the menu as per Figma design. You should use backdrop to have the same effect.
- [ ] Kindly make sure that for menu and for hamburger you follow the margin as given in the design. 
- [ ] Make sure to have margin to the left,right and top for the portfolio.
- [ ] Make sure to add top and right margin for mobile menu.

https://user-images.githubusercontent.com/70269507/174003018-26ce006b-5a68-4e3d-99bc-5a3a9a4dd220.mov

https://user-images.githubusercontent.com/70269507/174002973-89914ff3-852a-49e1-9bf9-5e12f738c889.mov

2022-06-16 08:43 UTC, Kossi-stack approved these changes
## Status: Approved ✔️
**Hi @Krishnabot,**

You did a really great job! 💯 💯💯💯
Congratulations! 🎉 🎉 🎉 🎉 🎉

![](https://user-images.githubusercontent.com/74506933/148243736-d9f63735-4cb1-411f-be28-34972618852d.gif)
You may close this Pull Request and merge the changes
Keep being awesome dev's and good luck with your next milestone!

## Optional suggestions
- [ ] kindly fix the about section in your next milestone use **padding-left**

![Capturepasd](https://user-images.githubusercontent.com/81444338/174030498-1784b265-de95-4b4d-b4e6-be47d89966f7.PNG)

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! 👏 👏 👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-06-16 08:53 UTC, merged